### ISSUE TITLE
"\r\n" not working

### ISSUE THREAD

**Issue by Dampfwalze** [damphat/json5-dart#13]
Imagine the following:
```
{
    "description": "This is some nice description \r\n- Each paragraph gets its own line\r\n- This is just the way it is"
}
```
this fails with: 
Unhandled Exception: SyntaxException: JSON5: invalid character '\r' at 2:47
#0      lexStates.<anonymous closure> (package:json5/src/parse.dart:593:9)
#1      lex (package:json5/src/parse.dart:104:40)
#2      parse (package:json5/src/parse.dart:28:13)
#3      json5Decode (package:json5/json5.dart:76:10)

only "\n" is expected too.

**Comment by damphat** [comment]
Use double slash `"\\n"` or `"\\r"` or `"\\r\\n"`. It is because you wrote your json string **directly into dart code**.

```
var json_str1 = ' "aaa \\r\\n bbb" ';

var json_str2 = ' "aaa \\n bbb" ';
```

Example:
```dart
import 'package:test/test.dart';

void main() {
  test('linebreaks', () {
    var obj = json5Decode('          '
        '{                           '
        '  "text": "aaa \\r\\n bbb"  '
        '}                           ');

    expect(obj['text'], 'aaa \r\n bbb');
  });
}

```

**Note: If you want "\r" or "\n", you can write & load json data from a text file instead**
